# Generated by Django 5.1.4 on 2024-12-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='task',
            field=models.CharField(default='exit', max_length=300),
            preserve_default=False,
        ),
    ]
