# Generated by Django 5.1.4 on 2024-12-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_people_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
